name: How Do I
description: I have a question how to use the mod
body:
  - type: markdown
    attributes:
      value: |
        ## **DO NOT USE THIS TRACKER FOR SUPPORT QUESTIONS**
        ### **Have you asked for help in our [Discord Server](https://discord.gg/23YCxmveUM)**
          if the answer is **NO** then go [there](https://discord.gg/23YCxmveUM) and ask your question!
          If, despite above, you still decide to open an issue there will be high probability that the answer will be "Go ask on Discord!"
  - type: dropdown
    attributes:
      label: Have you asked for help in discord?
      description:
      multiple: false
      options:
        - "NO"
        - "YES"
    validations:
      required: true
