# This is a basic workflow to help you get started with Actions

name: Automatic Release on version tag push

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the fabric-1.17 branch and tag matchin v*.*.*
  push:
    tags:
      - 'v*.*.*'
    branches: 
      - 'fabric-1.17'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/inventoryprofilesnext-fabric-1.17-?.?.?.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
